name: Run Web & API Tests on PR Merge

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-22.04  # More stable than ubuntu-latest for now

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          source .venv/bin/activate
          playwright install --with-deps

      - name: Run API Tests and Generate Report
        run: |
          source .venv/bin/activate
          pytest -m api --tb=short --disable-warnings --html=reports/api_report.html --self-contained-html

      - name: Run Web Tests and Generate Report
        run: |
          source .venv/bin/activate
          pytest -m web --tb=short --disable-warnings --html=reports/web_report.html --self-contained-html

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-reports
          path: reports/
